name: test install and output
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
env:
  HELM_VERSION: v3.8.0
  KUBE_CONFIG_PATH: ~/.kube/config

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: "1.19.x"

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0

      - name: Set up Helm
        uses: azure/setup-helm@v3.4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.14.x
          terraform_wrapper: false

      - name: Run go test
        run: |
          cd test; go test -v .
